# Generated by Django 4.0 on 2022-07-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.BigIntegerField()),
                ('Country', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Current_Organization', models.CharField(max_length=350)),
                ('Total_Experience', models.CharField(max_length=100)),
                ('Relavant_Experience', models.CharField(max_length=100)),
                ('Joining_Period', models.CharField(max_length=100)),
                ('Current_AnnualPay', models.CharField(max_length=100)),
                ('Expected_AnnualPay', models.CharField(max_length=100)),
                ('Position_AppliedFor', models.CharField(max_length=100)),
                ('Personal_Website', models.TextField()),
                ('LinkedIn_Profile', models.TextField()),
                ('Twitter_Url', models.TextField()),
                ('Resume', models.FileField(upload_to='Documents')),
                ('Discription', models.TextField()),
            ],
        ),
    ]
